### ISSUE TITLE
Bug: String encoding error in non-English environment.

### ISSUE THREAD

**Issue by longjunyu2** [tianocore/edk2-pytool-library#131]
Hello Developers,
When I use the lastest version of edk2-pytool-library to build Project mu, I meet the exception:
``` cmd
CRITICAL - Build Process Exception
ERROR - Traceback (most recent call last):
  File "d:\uefiworkspace\venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 152, in Go
    ret = self.Build()
  File "d:\uefiworkspace\venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 268, in Build
    ret = RunCmd("build", params)
  File "d:\uefiworkspace\venv\lib\site-packages\edk2toollib\utility_functions.py", line 187, in RunCmd
    thread.join()
  File "d:\uefiworkspace\venv\lib\site-packages\edk2toollib\utility_functions.py", line 70, in join
    raise self.exc
  File "d:\uefiworkspace\venv\lib\site-packages\edk2toollib\utility_functions.py", line 63, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "d:\uefiworkspace\venv\lib\site-packages\edk2toollib\utility_functions.py", line 90, in reader
    s = stream.readline().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 130: invalid start byte
```
I don't know about Python programming, but based on online search data, I think it might be caused by a string encoding format error.
My system language is Chinese, and the related compilation software is also installed in the Chinese environment. So I think this is the source of this error.
Expect this error to be fixed so that my work can continue.If you need more information, I can provide more logging and testing environments.

**Comment by spbrogan** [comment]
can you provide more of the log?  What is the build process doing at this time?  Basically everything in Edk2/Project Mu based projects should be in UTF-8 format.  If you look in both projects we run a test on all files to make sure they are UTF-8 encoded.  

That said it looks like it might be from running a tool and decoding the output string of the tool.
