### ISSUE TITLE
stuart_setup -c ./CISettings.py doesn't work on FreeBSD

### ISSUE THREAD

**Issue by bcran** [tianocore/edk2-pytool-library#26]
```
[bcran@photon ~/workspace/edk2-staging]$ stuart_setup -c ./CISettings.py 
Traceback (most recent call last):
  File "/home/bcran/.local/bin/stuart_setup", line 10, in <module>
    sys.exit(main())
  File "/home/bcran/.local/lib/python3.6/site-packages/edk2toolext/invocables/edk2_setup.py", line 196, in main
    Edk2PlatformSetup().Invoke()
  File "/home/bcran/.local/lib/python3.6/site-packages/edk2toolext/base_abstract_invocable.py", line 106, in Invoke
    self.ConfigureLogging()
  File "/home/bcran/.local/lib/python3.6/site-packages/edk2toolext/base_abstract_invocable.py", line 82, in ConfigureLogging
    edk2_logging.setup_console_logging(self.GetLoggingLevel("con"))
  File "/home/bcran/.local/lib/python3.6/site-packages/edk2toolext/edk2_logging.py", line 168, in setup_console_logging
    coloredHandler = ansi_handler.ColoredStreamHandler()
  File "/home/bcran/.local/lib/python3.6/site-packages/edk2toollib/log/ansi_handler.py", line 232, in __init__
    self.on_windows = GetHostInfo().os == "Windows"
  File "/home/bcran/.local/lib/python3.6/site-packages/edk2toollib/utility_functions.py", line 117, in GetHostInfo
    raise EnvironmentError("Host info could not be parsed: {0}".format(str(host_info)))
OSError: Host info could not be parsed: uname_result(system='FreeBSD', node='photon.int.bluestop.org', release='13.0-CURRENT', version='FreeBSD 13.0-CURRENT r352050 GENERIC-NODEBUG', machine='amd64', processor='amd64')
```

**Comment by matthewfcarlson** [comment]
@bcran thanks for bring up this issue! There's a PR up that should fix it, feel free to chime in if you have any opinions
