### ISSUE TITLE
Does not support "!if $(macro)" when macro is not defined

### ISSUE THREAD

**Issue by out0xb2** [tianocore/edk2-pytool-library#57]
Try to build OvmfPkg.

The FDFs specify:
```
!if $(E1000_ENABLE)
```
Results in:
```
DEBUG - Parse Active Platform DSC file: C:\git\edk2_py_ovmf\OvmfPkg/OvmfPkgIa32X64.dsc
DEBUG - Getting all build keys for build type DEBUG
DEBUG - Parse Active Flash Definition (FDF) file
DEBUG - Getting all build keys for build type DEBUG
ERROR - !if conditionals need to be formatted correctly (spaces between each token)
CRITICAL - Build Process Exception
ERROR - Traceback (most recent call last):
File "c:\git\venv_pytools\lib\site-packages\edk2toolext\environment\uefi_build.py", line 109, in Go
  ret = self.SetEnv()
File "c:\git\venv_pytools\lib\site-packages\edk2toolext\environment\uefi_build.py", line 384, in SetEnv 
  ret = self.ParseFdfFile()
File "c:\git\venv_pytools\lib\site-packages\edk2toolext\environment\uefi_build.py", line 523, in ParseFdfFile 
   fdf_parser.ParseFile(pa)
File "c:\git\venv_pytools\lib\site-packages\edk2toollib\uefi\edk2\parsers\dsc_parser.py", line 262, in ParseFile 
   self.__ProcessDefines(file_lines)
File "c:\git\venv_pytools\lib\site-packages\edk2toollib\uefi\edk2\parsers\dsc_parser.py", line 246, in __ProcessDefines 
   (line, add) = self.__ParseDefineLine(l) 
File "c:\git\venv_pytools\lib\site-packages\edk2toollib\uefi\edk2\parsers\dsc_parser.py", line 167, in __ParseDefineLine  
   if(self.ProcessConditional(line_resolved)):  
File "c:\git\venv_pytools\lib\site-packages\edk2toollib\uefi\edk2\parsers\base_parser.py", line 271, in ProcessConditional  
   raise Exception("Invalid conditional", text)
Exception: ('Invalid conditional', '!if $(E1000_ENABLE)')
``` 

The expected usage is that this define is not present.  If someone wants to add E1000 NIC support, the README advises: 
'
   Add "-D E1000_ENABLE" to your build command 
'

The spec says, "When used with the !if or !elseif statements or in an expression used in a value field, a macro that has not been defined has a value of 0".

**Comment by spbrogan** [comment]
This is already fixed in Release 0.10.4
